export enum AlphaVFunctions {
  TIME_SERIES_INTRADAY = 'TIME_SERIES_INTRADAY',
  TIME_SERIES_DAILY_ADJUSTED = 'TIME_SERIES_DAILY_ADJUSTED',
  GLOBAL_QUOTE = 'GLOBAL_QUOTE',
  TOP_GAINERS_LOSERS = 'TOP_GAINERS_LOSERS'
}
